app/Http/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the controller to call when that URI is requested.
|
*/

Route::get('/', function () {
    return view('welcome');
});

Route::auth();

Route::get('/home', 'HomeController@index');

Route::group(['prefix' => 'admin', 'middleware' => 'checkrole:admin', 'as' => 'admin.'], function(){
    
    Route::get('categories', ['as' => 'category.index', 'uses' => 'CategoryController@index']);
    Route::get('category/new', ['as' => 'category.new', 'uses' => 'CategoryController@create']);
    Route::post('category/store', ['as' => 'category.store', 'uses' => 'CategoryController@store']);
    Route::get('category/edit/{id}', ['as' => 'category.edit', 'uses' => 'CategoryController@edit']);
    Route::put('category/update/{id}', ['as' => 'category.update', 'uses' => 'CategoryController@update']);
    Route::get('category/destroy/{id}', ['as' => 'category.destroy', 'uses' => 'CategoryController@destroy']);

    Route::get('clients', ['as' => 'client.index', 'uses' => 'ClientController@index']);
    Route::get('client/new', ['as' => 'client.new', 'uses' => 'ClientController@create']);
    Route::post('client/store', ['as' => 'client.store', 'uses' => 'ClientController@store']);
    Route::get('client/edit/{id}', ['as' => 'client.edit', 'uses' => 'ClientController@edit']);
    Route::put('client/update/{id}', ['as' => 'client.update', 'uses' => 'ClientController@update']);
    Route::get('client/destroy/{id}', ['as' => 'client.destroy', 'uses' => 'ClientController@destroy']);
    
    Route::get('cupoms', ['as' => 'cupom.index', 'uses' => 'CupomController@index']);
    Route::get('cupom/new', ['as' => 'cupom.new', 'uses' => 'CupomController@create']);
    Route::post('cupom/store', ['as' => 'cupom.store', 'uses' => 'CupomController@store']);
    Route::get('cupom/edit/{id}', ['as' => 'cupom.edit', 'uses' => 'CupomController@edit']);
    Route::put('cupom/update/{id}', ['as' => 'cupom.update', 'uses' => 'CupomController@update']);
    Route::get('cupom/destroy/{id}', ['as' => 'cupom.destroy', 'uses' => 'CupomController@destroy']);
    
    Route::get('order', ['as' => 'order.index', 'uses' => 'OrderController@index']);
    Route::get('order/edit/{id}', ['as' => 'order.edit', 'uses' => 'OrderController@edit']);
    Route::put('order/update/{id}', ['as' => 'order.update', 'uses' => 'OrderController@update']);
    
    Route::get('products', ['as' => 'product.index', 'uses' => 'ProductController@index']);
    Route::get('product/new', ['as' => 'product.new', 'uses' => 'ProductController@create']);
    Route::post('product/store', ['as' => 'product.store', 'uses' => 'ProductController@store']);
    Route::get('product/edit/{id}', ['as' => 'product.edit', 'uses' => 'ProductController@edit']);
    Route::put('product/update/{id}', ['as' => 'product.update', 'uses' => 'ProductController@update']);
    Route::get('product/destroy/{id}', ['as' => 'product.destroy', 'uses' => 'ProductController@destroy']);
    
    
});

Route::group(['prefix' => 'customer', 'middleware' => 'checkrole:client', 'as' => 'customer.'], function(){
    Route::get('order', ['as' => 'order.index', 'uses' => 'CheckoutController@index']);
    Route::get('order/new', ['as' => 'order.new', 'uses' => 'CheckoutController@create']);
    Route::post('order/store', ['as' => 'order.store', 'uses' => 'CheckoutController@store']);
});

Route::group(['middleware' => 'cors'], function() {
    
    Route::post('oauth/access_token', function() {
      return Response::json(Authorizer::issueAccessToken());
    });
    
    Route::get('authenticated', function(){
        $idUser = Authorizer::getResourceOwnerId();
        return \Delivery\Models\User::find($idUser);
    });
    
    Route::group(['prefix' => 'api', 'middleware' => 'oauth', 'as' => 'api.'], function(){

        Route::group(['prefix' => 'client', 'middlewere' => 'auth.checkrole:client', 'as' => 'client.'], function(){

            Route::resource('order', 'Api\Client\ClientCheckoutController', ['except' => ['create', 'edit', 'destroy']]);
            Route::get('products', 'Api\Client\ClientProductController@index');
        });

        Route::group(['prefix' => 'deliveryman', 'middleware' => 'auth.checkrole:deliveryman', 'as' => 'deliveryman.'], function(){
            Route::resource('order', 'Api\Deliveryman\DeliverymanCheckoutController', ['except' => ['create', 'edit', 'destroy', 'store']]);

            Route::patch('order/{id}/update-status', 'Api\Deliveryman\DeliverymanCheckoutController@updateStatus', 
                    ['as' => 'orders.update_status']);
        });
    });
});

app/Models/Client.php
<?php

namespace Delivery\Models;

use Illuminate\Database\Eloquent\Model;
use Prettus\Repository\Contracts\Transformable;
use Prettus\Repository\Traits\TransformableTrait;

class Client extends Model implements Transformable
{
    use TransformableTrait;

    protected $fillable = [
        'user_id',
        'phone',
        'address',
        'city',
        'state',
        'zipcode',
    ];
    
    public function user()
    {
        return $this->hasOne(User::class, 'id', 'user_id');
    }
    
    public function orders()
    {
        return $this->hasMany(Order::class);
    }

}

app/Http/Controllers/Api/Client/ClientCheckoutController.php
<?php

namespace Delivery\Http\Controllers\Api\Client;

use Delivery\Http\Controllers\Controller;
use Delivery\Repositories\OrderRepository;
use Delivery\Repositories\UserRepository;
use Delivery\Services\OrderService;
use LucaDegasperi\OAuth2Server\Facades\Authorizer;
use Delivery\Http\Requests\Api\CheckoutRequest;

class ClientCheckoutController extends Controller
{
    protected $orderRepository;
    protected $userRepository;
    protected $orderService;
    protected $with =['client', 'cupom', 'items'];
    
    public function __construct(
        OrderRepository $orderRepository,
        UserRepository  $userRepository,
        OrderService  $orderService
    ) 
    {
        $this->orderRepository   = $orderRepository;
        $this->userRepository    = $userRepository;
        $this->orderService      = $orderService;
    }
    
    public function index() 
    {
        $clientId = $this->userRepository->find(Authorizer::getResourceOwnerId())->client->id;
        $orders   = $this->orderRepository->skipPresenter(false)->with($this->with)->scopeQuery(function($query) use($clientId){
            return $query->where('client_id', $clientId);
        })->paginate();
        return $orders;
    }
    
    public function store(CheckoutRequest $request)
    {
        $data              = $request->all();
        $clientId          = $this->userRepository->find(Authorizer::getResourceOwnerId())->client->id;
        $data['client_id'] = $clientId;
        $order             = $this->orderService->create($data);
        return $this->orderRepository->skipPresenter()->find($order->id);
    }
    
    public function show($id)
    {
        return $this->orderRepository->skipPresenter(false)->with($this->with)->find($id);
    }
   
}

app/Http/Controllers/Api/Client/ClientProductController.php
<?php

namespace Delivery\Http\Controllers\Api\Client;

use Delivery\Http\Controllers\Controller;
use Delivery\Repositories\ProductRepository;

class ClientProductController extends Controller
{
    /**
     *ProductRepository
     * @var type 
     */
    protected $repository;
    
    public function __construct(ProductRepository $repository) 
    {
        $this->repository   = $repository;
    }
    
    public function index() 
    {
        $products = $this->repository->skipPresenter(false)->all();
        return $products;
    }
}

app/Http/Controllers/ClientController.php
<?php

namespace Delivery\Http\Controllers;

use Delivery\Repositories\ClientRepository;
Use Delivery\Repositories\UserRepository;
use Delivery\Services\ClientService;
use Delivery\Http\Requests\AdminClientRequest;

class ClientController extends Controller
{
    protected $repository;
    protected $userRepository;
    protected $service;


    public function __construct(ClientRepository $repository, UserRepository $userRepository, ClientService $service) 
    {
        $this->repository     = $repository;
        $this->userRepository = $userRepository;
        $this->service        = $service;
    }
    public function index()
    {
        $clients = $this->repository->orderBy('id', 'desc')->with(['user'])->paginate(10);
        return view('admin.client.index', compact('clients'));
    }
    
    public function create()
    {
        return view('admin.client.new');
    }
    
    public function store(AdminClientRequest $request)
    {
        $this->service->create($request->all());
        
        return redirect()->route('admin.client.index');
    }
    
    public function edit($id)
    {
        $client = $this->repository->find($id);
        return view('admin.client.edit', compact('client', 'users'));
    }
    
    public function update(AdminClientRequest $request, $id)
    {
        $this->service->update($request->all(), $id);
        return redirect()->route('admin.client.index');
    }
    
    public function destroy($id)
    {
        $this->repository->delete($id);
        return redirect()->route('admin.client.index');
    }
}

resources/views/admin/client/_form.blade.php
<div class="form-group">
    {!! Form::label('Name', 'Nome') !!}
    {!! Form::text('user[name]', null, ['class' => 'form-control'])!!}
</div>

<div class="form-group">
    {!! Form::label('Email', 'E-mail') !!}
    {!! Form::text('user[email]', null, ['class' => 'form-control'])!!}
</div>

<div class="form-group">
    {!! Form::label('Phone', 'Telefone') !!}
    {!! Form::text('phone', null, ['class' => 'form-control'])!!}
</div>

<div class="form-group">
    {!! Form::label('Address', 'Endereço') !!}
    {!! Form::text('address', null, ['class' => 'form-control'])!!}
</div>

<div class="form-group">
    {!! Form::label('State', 'Estado') !!}
    {!! Form::text('state', null, ['class' => 'form-control'])!!}
</div>

<div class="form-group">
    {!! Form::label('City', 'Cidade') !!}
    {!! Form::text('city', null, ['class' => 'form-control'])!!}
</div>

<div class="form-group">
    {!! Form::label('Zipcode', 'CEP') !!}
    {!! Form::text('zipcode', null, ['class' => 'form-control'])!!}
</div>
                   

resources/views/admin/client/edit.blade.php
@extends('app')

@section('content')

<div class="container">
	<div class="row">
		<div class="col-md-10 col-md-offset-1">
                       @include('errors.checkError')
			<div class="panel panel-default">
                            <div class="panel-heading">
                                Editar Cliente - {{$client->user->name}}
                                <a href="{{url()->previous()}}" class="pull-right">Voltar</a>
                            </div>
                            <div class="panel-body">
                                <!--Model faz um bind nos campos dos formulário-->
                                {!! Form::model($client, ['route' => ['admin.client.update', $client->id], 'method' => 'put']) !!}
                                @include('admin.client._form')
                                
                                <div class="form-group">
                                    {!! Form::submit('Gravar', ['class' => 'btn btn-primary']) !!}
                                </div>
                                
                                {!! Form::close()!!}
                            </div>
			</div>
		</div>
	</div>
</div>
@endsection

resources/views/admin/client/index.blade.php
@extends('app')

@section('content')

<div class="container">
	<div class="row">
		<div class="col-md-10 col-md-offset-1">
			<div class="panel panel-default">
                            <div class="panel-heading">
                                Produtos 
                                <a href="{{route('admin.client.new')}}" class="pull-right">Novo Cliente</a>
                            </div>

                            <div class="panel-body">
                                <table class="table table-striped table-condensed table-hover">
                                    <thead>
                                        <tr>
                                            <th>#</th>
                                            <th>Cliente</th>
                                            <th>Telefone</th>
                                            <th>Estado</th>
                                            <th>Cidade</th>
                                            <th>CEP</th>
                                            <th colspan="2" class="text-center">Ação</th>
                                        </tr>
                                    </thead>
                                    <tbody>
                                        @foreach($clients as $client)
                                        <tr>
                                            <td>{{$client->id}}</td>
                                            <td>{{$client->user->name}}</td>
                                            <td>{{$client->phone}}</td>
                                            <td>{{$client->state}}</td>
                                            <td>{{$client->city}}</td>
                                            <td>{{$client->zipcode}}</td>
                                            <td><a href="{{route('admin.client.edit', ['id' => $client->id])}}" class="btn">Editar</a></td>
                                            <td><a href="{{route('admin.client.destroy', ['id' => $client->id])}}" class="btn">Excluir</a></td>
                                        </tr>
                                        @endforeach
                                    </tbody>
                                </table>
                                {!!$clients->render()!!}
                            </div>
			</div>
		</div>
	</div>
</div>
@endsection

resources/views/admin/client/new.blade.php
@extends('app')

@section('content')

<div class="container">
	<div class="row">
		<div class="col-md-10 col-md-offset-1">
                        @include('errors.checkError')
			<div class="panel panel-default">
                            <div class="panel-heading">
                                Novo Cliente
                                <a href="{{url()->previous()}}" class="pull-right">Voltar</a>
                            </div>
                            <div class="panel-body">
                                <!--Model faz um bind nos campos dos formulário-->
                                {!! Form::open(['route' => 'admin.client.store']) !!}
                                @include('admin.client._form')
                                
                                <div class="form-group">
                                    {!! Form::submit('Gravar', ['class' => 'btn btn-primary']) !!}
                                </div>
                                {!! Form::close()!!}
                            </div>
			</div>
		</div>
	</div>
</div>
@endsection