app/Http/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the controller to call when that URI is requested.
|
*/

Route::get('/', function () {
    return view('welcome');
});

Route::auth();

Route::get('/home', 'HomeController@index');

Route::group(['prefix' => 'admin', 'middleware' => 'checkrole:admin', 'as' => 'admin.'], function(){
    
    Route::get('categories', ['as' => 'category.index', 'uses' => 'CategoryController@index']);
    Route::get('category/new', ['as' => 'category.new', 'uses' => 'CategoryController@create']);
    Route::post('category/store', ['as' => 'category.store', 'uses' => 'CategoryController@store']);
    Route::get('category/edit/{id}', ['as' => 'category.edit', 'uses' => 'CategoryController@edit']);
    Route::put('category/update/{id}', ['as' => 'category.update', 'uses' => 'CategoryController@update']);
    Route::get('category/destroy/{id}', ['as' => 'category.destroy', 'uses' => 'CategoryController@destroy']);

    Route::get('clients', ['as' => 'client.index', 'uses' => 'ClientController@index']);
    Route::get('client/new', ['as' => 'client.new', 'uses' => 'ClientController@create']);
    Route::post('client/store', ['as' => 'client.store', 'uses' => 'ClientController@store']);
    Route::get('client/edit/{id}', ['as' => 'client.edit', 'uses' => 'ClientController@edit']);
    Route::put('client/update/{id}', ['as' => 'client.update', 'uses' => 'ClientController@update']);
    Route::get('client/destroy/{id}', ['as' => 'client.destroy', 'uses' => 'ClientController@destroy']);
    
    Route::get('cupoms', ['as' => 'cupom.index', 'uses' => 'CupomController@index']);
    Route::get('cupom/new', ['as' => 'cupom.new', 'uses' => 'CupomController@create']);
    Route::post('cupom/store', ['as' => 'cupom.store', 'uses' => 'CupomController@store']);
    Route::get('cupom/edit/{id}', ['as' => 'cupom.edit', 'uses' => 'CupomController@edit']);
    Route::put('cupom/update/{id}', ['as' => 'cupom.update', 'uses' => 'CupomController@update']);
    Route::get('cupom/destroy/{id}', ['as' => 'cupom.destroy', 'uses' => 'CupomController@destroy']);
    
    Route::get('order', ['as' => 'order.index', 'uses' => 'OrderController@index']);
    Route::get('order/edit/{id}', ['as' => 'order.edit', 'uses' => 'OrderController@edit']);
    Route::put('order/update/{id}', ['as' => 'order.update', 'uses' => 'OrderController@update']);
    
    Route::get('products', ['as' => 'product.index', 'uses' => 'ProductController@index']);
    Route::get('product/new', ['as' => 'product.new', 'uses' => 'ProductController@create']);
    Route::post('product/store', ['as' => 'product.store', 'uses' => 'ProductController@store']);
    Route::get('product/edit/{id}', ['as' => 'product.edit', 'uses' => 'ProductController@edit']);
    Route::put('product/update/{id}', ['as' => 'product.update', 'uses' => 'ProductController@update']);
    Route::get('product/destroy/{id}', ['as' => 'product.destroy', 'uses' => 'ProductController@destroy']);
    
    
});

Route::group(['prefix' => 'customer', 'middleware' => 'checkrole:client', 'as' => 'customer.'], function(){
    Route::get('order', ['as' => 'order.index', 'uses' => 'CheckoutController@index']);
    Route::get('order/new', ['as' => 'order.new', 'uses' => 'CheckoutController@create']);
    Route::post('order/store', ['as' => 'order.store', 'uses' => 'CheckoutController@store']);
});

Route::group(['middleware' => 'cors'], function() {
    
    Route::post('oauth/access_token', function() {
      return Response::json(Authorizer::issueAccessToken());
    });
    
    Route::get('authenticated', function(){
        $idUser = Authorizer::getResourceOwnerId();
        return \Delivery\Models\User::find($idUser);
    });
    
    Route::group(['prefix' => 'api', 'middleware' => 'oauth', 'as' => 'api.'], function(){

        Route::group(['prefix' => 'client', 'middlewere' => 'auth.checkrole:client', 'as' => 'client.'], function(){

            Route::resource('order', 'Api\Client\ClientCheckoutController', ['except' => ['create', 'edit', 'destroy']]);
            Route::get('products', 'Api\Client\ClientProductController@index');
        });

        Route::group(['prefix' => 'deliveryman', 'middleware' => 'auth.checkrole:deliveryman', 'as' => 'deliveryman.'], function(){
            Route::resource('order', 'Api\Deliveryman\DeliverymanCheckoutController', ['except' => ['create', 'edit', 'destroy', 'store']]);

            Route::patch('order/{id}/update-status', 'Api\Deliveryman\DeliverymanCheckoutController@updateStatus', 
                    ['as' => 'orders.update_status']);
        });
    });
});

app/Models/Order.php
<?php

namespace Delivery\Models;

use Illuminate\Database\Eloquent\Model;
use Prettus\Repository\Contracts\Transformable;
use Prettus\Repository\Traits\TransformableTrait;

class Order extends Model implements Transformable
{
    use TransformableTrait;

    protected $fillable = [
        'client_id',
        'user_deliveryman_id',
        'cupom_id',
        'total',
        'status',
    ];
    
    public function client()
    {
        return $this->belongsTo(Client::class);
    }
    
    public function items()
    {
        return $this->hasMany(OrderItem::class);
    }
    
    public function deliveryman()
    {
        return $this->belongsTo(User::class, 'user_deliveryman_id');
    }
    
    public function cupom()
    {
        return $this->belongsTo(Cupom::class);
    }

}

app/Http/Controllers/OrderController.php
<?php

namespace Delivery\Http\Controllers;

use Illuminate\Http\Request;
use Delivery\Repositories\OrderRepository;
use Delivery\Repositories\UserRepository;
use Delivery\Models\Core;

class OrderController extends Controller
{
    protected $repository;
    protected $userRepository;
    
    
    public function __construct(OrderRepository $respository, UserRepository $userRepository) 
    {
        $this->repository     = $respository;
        $this->userRepository = $userRepository;
    }
    
    public function index()
    {
        $orders = $this->repository->orderBy('id', 'desc')->paginate(10);
        return view('admin.order.index', compact('orders'));
    }
    
    public function edit($id)
    {
        $order = $this->repository->find($id);
        
        $listaStatus = Core::status();
        
        $deliveryman = $this->userRepository->orderBy('name')->findWhere(['role' => 'deliveryman'])->lists('name', 'id');
       
        return view('admin.order.edit', compact('order', 'listaStatus', 'deliveryman'));
    }
    
    public function update(Request $request, $id)
    {
        $this->repository->update($request->all(), $id);
        return redirect()->route('admin.order.index');
    }
}

resources/views/customer/order/index.blade.php
@extends('app')

@section('content')
<div class="container">
    <h3>Meu(s) Pedido(s)</h3>
    <a href="{{route('customer.order.new')}}" class="pull-right">Novo pedido</a>
    <table class="table table-striped table-condensed table-hover">
        <thead>
            <tr>
                <th>#</th>
                <!--<th>Produto</th>-->
                <th>Total</th>
                <th>Status</th>
            </tr>
        </thead>
        <tbody>
            <tbody>
                @foreach($orders as $order)
                <tr>
                    <td>{{$order->id}}</td>
                    <td>{{$order->total}}</td>
                    <td>{{$order->status}}</td>
                </tr>
                @endforeach
            </tbody>
        </tbody>
    </table>
    {!!$orders->render()!!}
</div>
@endsection

resources/views/customer/order/new.blade.php
@extends('app')

@section('content')
<div class="container">
    <h3>Novo Pedido</h3>
    @include('errors.checkError')
    <div class="container">
    {!! Form::open(['route' => 'customer.order.store', 'class' => 'form']) !!}
    <div class="form-group">
        <label>Total: </label>
        <p id="total"></p>
        <a href="#" id="btnNew" class="btn btn-default">Novo item</a>
        <table class="table table-striped table-condensed table-hover">
            <thead>
                <tr>
                    <th>Produto</th>
                    <th>Quantidade</th>
                </tr>
            </thead>
            <tbody>
                <tr>
                    <td>
                        <select class="form-control" name="items[0][product_id]">
                            @foreach($products as $product)
                                <option value="{{$product->id}}" data-price="{{$product->price}}">
                                    {{$product->name}} -- R${{$product->price}}
                                </option>
                            @endforeach
                        </select>
                    </td>
                    <td>{!!Form::number('items[0][quantidade]', 1, ['class' => 'form-control']) !!}</td>
                </tr>
            </tbody>
        </table>
    </div>
    <div class="form-group">
        {!! Form::submit('Finalizar', ['class' => 'btn btn-primary']) !!}
    </div>
    {!! Form::close()!!}
    </div>
@endsection

@section('script')
<script>
    $('#btnNew').click(function(){
        var row = $('table tbody > tr:last'), 
            newRow = row.clone(), 
            length = $('table tbody tr').length;
            
        newRow.find('td').each(function(){
           var td     = $(this), 
               input  = td.find('input,select'), 
               name   = input.attr('name');
           input.attr('name', name.replace((length - 1) + "", length + ""));
        });
        
        newRow.find('input').val(1);
        newRow.insertAfter(row);
        calculateTotal();
    });
    
    $(document.body).on('click', 'select', function(){
        calculateTotal();
    });
    
    $(document.body).on('blur', 'input', function(){
        calculateTotal();
    });
    
    function calculateTotal()
    {
        var total = 0,
            trLen = $('table tbody tr').length,
            tr    = null,
            price,
            quantidade;
        for (var i =0; i < trLen; i++) {
            tr         = $('table tbody tr').eq(i);
            price      = tr.find(':selected').data('price');
            quantidade = tr.find('input').val();
            total += price * quantidade;
        }
        $('#total').html(total);
    }
</script>
@endsection